### ISSUE TITLE
cdnjs link is broken

### ISSUE THREAD

**Issue by aknuds1** [ramda/ramda.github.io#87] opened 2016-06-24 10:12 UTC
The cdnjs link is as of version 0.21.0 broken: `<script src="//cdnjs.cloudflare.com/ajax/libs/ramda/ramda.min.js"/"ramda.min.js"/"ramda.min.js"/"0.21/ramda.min.js"/ramda.min.js".1/ramda.min.js"/ramda.min.js"></script>`.

AFAICT it should rather be `<script src="//cdnjs.cloudflare.com/ajax/libs/ramda/0.21.0/ramda.min.js"></script>`.

**Comment by CrossEye** [comment] 2016-06-28 01:22
Wow, that's nasty!  If anyone can look at it before I get a chance (not likely before the weekend) feel free!

**Comment by aknuds1** [comment] 2016-06-28 08:10
@CrossEye I asked in the Gitter channel on how to fix this, but never received an answer as far as I can tell. I have forked the corresponding Git repository, but couldn't figure out how the web page is generated in order to make the necessary changes. What should I do?

**Comment by buzzdecafe** [comment] 2016-06-28 14:40
i am guessing, but i that error looks like it is generated as part of the `prepublish` script: https://github.com/ramda/ramda/blob/master/scripts/prepublish

**Comment by aknuds1** [comment] 2016-06-28 14:49
@buzzdecafe Looks as if that updates the README in the ramda repository, and doesn't affect this repo, which is the one in question.

**Comment by buzzdecafe** [comment] 2016-06-28 15:31
@aknuds1 look at the README in the published artifact here: https://github.com/ramda/ramda/archive/v0.21.0.zip

I think you will see the same malformed cdnjs url. this supports my hypothesis that the `prepublish` script is where the problem lies.

**Comment by aknuds1** [comment] 2016-06-28 15:34
@buzzdecafe Well, AFAICT from prepublish though, it only modifies README.md and also ensures that README.md is updated in git (well, it doesn't commit it, but it does add it to the staging area).

The README's cdn links look OK though.

**Comment by aknuds1** [comment] 2016-06-28 15:35
Anyhow, I await a canonical answer on how to fix this repo.

**Comment by aknuds1** [comment] 2016-06-28 15:37
@buzzdecafe Hm... when comparing the README and the website it does look as if they are the same. Is the README copied to this repo somehow?

**Comment by aknuds1** [comment] 2016-06-28 15:38
[This](https://github.com/ramda/ramda/commit/99e3fe64237d82262f97a9c8c908f34e9e2b165b) is an interesting commit...

**Comment by buzzdecafe** [comment] 2016-06-28 15:38
yeah i was trying to track down where that happens. looks like it's in the Makefile. but i believe the root of the problem is in the prepublish script

**Comment by aknuds1** [comment] 2016-06-28 15:39
I guess the question is how the README is used to update this repo.

**Comment by buzzdecafe** [comment] 2016-06-28 15:40
looks like prepublish was producing garbage links, but it got fixed manually. thanks to you pursuing this, we have the opportunity to fix the root problem

**Comment by davidchambers** [comment] 2016-06-28 17:34
I see the problem. There was a bug in GNU bash that was fixed at some point between versions 3.2.57 and 4.3.42. @asaf-romano must have a default `bash` which predates the bug fix.

```console
$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

$ /opt/local/bin/bash --version
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.0.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ /bin/bash -c 's="foo/bar/baz"; echo "${s//"bar/baz"/"BAR/BAZ"}"'
foo/baz"/"BAR/BAZ"/baz

$ /opt/local/bin/bash -c 's="foo/bar/baz"; echo "${s//"bar/baz"/"BAR/BAZ"}"'
foo/BAR/BAZ
```

Note that the first slash (`/`) after the double slash (`//`) is meant to be part of the pattern but is misinterpreted as a delimiter by the older version.

I'll rewrite the line to be compatible with old versions of GNU bash.

**Comment by buzzdecafe** [comment] 2016-06-28 17:38
@davidchambers could be as simple as `cat README.md | sed s/${PREVIOUS_VERSION}/${VERSION}/`?

**Comment by davidchambers** [comment] 2016-06-28 17:45
That could happen to match unrelated version numbers. I'd prefer to be explicit. The fix is not complex.

**Comment by CrossEye** [comment] 2016-06-29 04:17
> @CrossEye I asked in the Gitter channel on how to fix this, but never received an answer as far as I can tell

I apologize.  I think that was me.  I usually am at least somewhat active in Gitter.  But today was my third pass at a root canal.  I haven't been focused much on coding outside my day job.  I'm hoping today finally fixed the - ahem - root cause of the issue, and that I can pay better attention.  I'm sorry your question got dropped there.

**Comment by aknuds1** [comment] 2016-06-29 07:40
No worries @CrossEye

**Comment by buzzdecafe** [comment] 2016-06-29 12:16
closed by https://github.com/ramda/ramda/pull/1811

thanks for following up on this @aknuds1

**Comment by davidchambers** [comment] 2016-06-30 22:45
Let's keep this open until the fix has actually been applied to the website. I'll look into it now.

**Closed** 2016-07-01 01:35 UTC
